main: su.nightexpress.excellentenchants.ExcellentEnchants
version: '${project.version}'
name: ExcellentEnchants
author: NightExpress
desciption: Vanilla-like enchants for your server.
depend: [ NexEngine ]
softdepend: [ ProtocolLib, NoCheatPlus, PlaceholderAPI, MythicMobs ]
api-version: 1.18
load: STARTUP