name: ExcellentEnchants
version: '${project.version}'
main: su.nightexpress.excellentenchants.PaperEnchantsPlugin
bootstrapper: su.nightexpress.excellentenchants.ExcellentBootstrapper
api-version: '1.21.4'
authors: [ NightExpress, ArikSquad ]
desciption: A lot of new enchantments properly integrated into the server!
load: STARTUP
dependencies:
  server:
    nightcore:
      load: BEFORE
      required: true
    ProtocolLib:
      load: BEFORE
      required: false
    packetevents:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    MythicMobs:
      load: BEFORE
      required: false


